---
- name: Ansible Install Jenkins on Ubuntu18 Server
  gather_facts: false
  become: true
  hosts: localhost
  tasks:

    - name: Install Java
      shell: sudo apt install -y openjdk-8-jdk

    - name: Install key for the Jenkins apt repository
      apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
        state: present

    - name: Install access to the Jenkins apt repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: 'jenkins-stable'
        update_cache: yes

    - name: Install Jenkins package
      apt:
        name: jenkins

    - name: Wait for Jenkins to start up
      wait_for: timeout=35

    - name: Start Jenkins service 
      service:
        name: jenkins
        state: started
        enabled: yes